### ISSUE TITLE
TODO for first version

### ISSUE THREAD

**Issue by shakacode** [shakacode/react_on_rails#1]
## Completed:
- [x] Support for both React 0.13 and 0.14
- [x] Port console polyfill from react-rails #8
- [x] Make work with turbolinks
- [x] Modify render_component helper to put JSON data javascript
      adjacent to react component.
- [x] Move over the javascript/webpack/node stuff to this repo
- [x] Create a PR on the https://github.com/shakacode/react-webpack-rails-tutorial that is the simplest thing, which is just including the gem but no server rendering.
- [x] Lots of options to add later to allow customization
- [x] Add linting and CI scripts
- [x] Support both an api of a function that takes props or a react component #11 
- [x] Make the name of the 'generated/server.js' configurable #9
- [x] Port other js engine options from react-rails  #28
- [x] Create a second PR (or just new branch) based on the last commit (if not merged to master) that shows the change to make this enabled for server rendering.
- [x] Change the default of prerender to false, because it takes extra care to create a react component that can prerender. Make this configurable so the config file #12 
- [x] XSS vulnerability: serialization of props, exposed on the client, #47 
- [x] Add integration test, #45 
- [x] Lots of docs on the webpack setup
- [x] If no generated/server.js exists, then do not include the file, #14

**Comment by justin808** [comment]
Action Plan for @skv-headless on August 30, 2015.

- [ ] If no generated/server.js exists, then do not include the file, #14 
- [ ] Change the default of prerender to false, because it takes extra care to create a react component that can prerender. Make this configurable so the config file #12 
- [ ] Change the spec/dummy app to support the points above, and update the docs.
- [ ] Create a PR on the https://github.com/shakacode/react-webpack-rails-tutorial that is the simplest thing, which is just including the gem but no server rendering.
- [ ] Create a generator to create the default webpack config.
- [ ] Create a second PR (or just new branch) based on the last commit (if not merged to master) that shows the change to make this enabled for server rendering.

**Comment by justin808** [comment]
@skv-headless, @alexfedoseev How's this list going? Possibly we can open up some of the tasks for others to do?

**Comment by ilyadoroshin** [comment]
@justin808 :+1:

**Comment by justin808** [comment]
@ilyadoroshin Any chance that you can give us a hand? I'm happy to skype with you to discuss this project.

**Comment by ilyadoroshin** [comment]
@justin808 maybe hangouts will do? I'd love to help, actually :)

**Comment by justin808** [comment]
Please send me your email justin@shakakcode.com, and we'll get you in our slack collab room, and get going. CC: @alexfedoseev

**Comment by ilyadoroshin** [comment]
Delivery to the following recipient failed permanently: justin@shakakcode.com
I guess, you meant justin@shakacode.com

**Comment by justin808** [comment]
Closing this issue now, as we're at 1.0.0.pre.
