### ISSUE TITLE
1.1.0 Release Place Holder

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#107]
Here's a list of the issues I'd like to see in 1.1.0:

## Must Haves
- [x] Turbolinks issues, #105
- [x] React Router support #106
- [x] Error and redirect handling #69

## Nice to Haves
- [ ] Bootstrap as an option #96

**Comment by robwise** [comment]
Implemented in https://github.com/shakacode/react_on_rails/commit/4d028bf59e937d1391a1269ef3abf3ada14cc116
