### ISSUE TITLE
Checklist of needed updates

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#1267]
- [ ] Update all referenced node modules
- [ ] Update all referenced gems
- [ ] Double-check all docs for contributing
- [ ] Double-check all docs for API
- [ ] Double-check spec/dummy app for ease of use for development
